import { Metadata } from "next";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export const metadata: Metadata = {
  title: "Home | Nutrify",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <header></header>
      <main></main>
    </div>
  );
}
