import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home | Nutrify",
  description: "Generated by create next app",
};

export default function Home() {
  return <h1>Nutrify</h1>;
}
