import { Metadata } from 'next';

import { RecommendationFood, BackgroundProvider } from '@/components';
import { FloatingBubbles } from '@/components/main/FloatingBubbles';

export const metadata: Metadata = {
  title: 'Home | Nutrify',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <div>
      <FloatingBubbles />
      <section className="relative w-full h-[500] lg:h-screen mt-0">
        <BackgroundProvider />
        <div className="absolute inset-0 flex flex-col justify-center">
          <div className="container mx-auto px-4">
            <h1 className="text-2xl md:text-3xl lg:text-4xl font-bold ">
              Kenali <span className="text-orange-500">Makanan</span> di Sekitarmu,
              <br /> Jaga <span className="text-green-700">Kesehatan</span>mu
            </h1>
            <p className="mt-2 text-sm md:text-lg text-gray-500">
              Temukan informasi nutrisi, tips sehat, dan inspirasi <br />
              gaya hidup mulai dari apa yang kamu makan.
            </p>
          </div>
        </div>
      </section>
      <main>
        <section className="container mx-auto px-4 py-10 lg:py-20 text-center">
          <h1>
            Tentang <span className="text-orange-500">Nutrify</span>
          </h1>
          <p className="lg:w-250 mt-3 mx-auto">
            Nutrify adalah panduan nutrisi cerdas Anda, yang dirancang untuk membantu Anda membuat pilihan makanan yang tepat sesuai dengan kondisi kesehatan Anda. Basis data makanan kami yang komprehensif, diperkaya dengan penandaan khusus
            dan kemampuan AI terintegrasi, memberdayakan Anda untuk dengan mudah mengidentifikasi makanan yang bermanfaat atau sebaiknya dihindari. Nutrify menyederhanakan pola makan sehat, menempatkan panduan nutrisi yang dipersonalisasi
            langsung di ujung jari Anda.
          </p>
        </section>
        {/* Recommendation */}
        <RecommendationFood />
      </main>
    </div>
  );
}
