import { Metadata } from "next";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

import RecommendationFood from "@/components/features/RecommendationFood";
import BackgroundProvider from "@/components/features/BackgroundProvider";

export const metadata: Metadata = {
  title: "Home | Nutrify",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <section className="relative w-full h-[500] lg:h-screen mt-0">
        <BackgroundProvider />
        <div className="absolute inset-0 flex flex-col justify-center">
          <div className="container mx-auto px-4">
            <h1 className="text-2xl md:text-3xl lg:text-4xl font-bold ">
              Kenali <span className="text-orange-500">Makanan</span> di Sekitarmu,
              <br /> Jaga <span className="text-green-700">Kesehatan</span>mu
            </h1>
            <p className="mt-2 text-sm md:text-lg text-gray-500">
              Temukan informasi nutrisi, tips sehat, dan inspirasi <br />
              gaya hidup mulai dari apa yang kamu makan.
            </p>
            <div className="flex mt-10 max-w-md">
              <Input placeholder="Cari Makanan atau Minuman..." className="shadow-none border-none rounded-r-none h-13 focus-visible:ring-offset-0 focus-visible:ring-0 bg-white" />
              <Button type="submit" className="rounded-l-none h-13 w-25">
                Explore
              </Button>
            </div>
          </div>
        </div>
      </section>
      <main>
        {/* About Us */}
        <section className="container mx-auto px-4 py-10 lg:py-20 text-center">
          <h1>
            Tentang <span className="text-orange-500">Nutrify</span>
          </h1>
          <p className="lg:w-250 mt-3 mx-auto">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati possimus sed architecto, impedit mollitia vero voluptatibus iste officia, tempore temporibus aliquam quidem harum accusantium perspiciatis adipisci nemo
            aperiam. Consectetur architecto, aperiam nihil illo hic voluptatem? Ducimus ut numquam nihil cum.
          </p>
        </section>
        {/* Recommendation */}
        <RecommendationFood />
      </main>
    </div>
  );
}
